root: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    jsx: true
    destructuring: true
    spread: true

settings:
  import/resolver: webpack

env:
  browser: true

plugins:
  - react

extends: airbnb

rules:
  func-names: off
  no-unused-vars: warn
  semi: [warn, never]
  new-cap: off
  quotes: [warn, single]
  react/prefer-stateless-function: off
  import/prefer-default-export: off
  linebreak-style: off
  class-methods-use-this: off
  import/imports-first: off
  no-mixed-operators: off
  no-else-return: off
  jsx-a11y/no-static-element-interactions: off
  react/forbid-prop-types: off
